### ISSUE TITLE
Fail to compile

### ISSUE THREAD

**Issue by kthakore** [tsee/ZeroMQ-Perl#3]
I get this one make run

g++ -c  -I. -D_REENTRANT -D_GNU_SOURCE -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2   -DVERSION=\"0.01\" -DXS_VERSION=\"0.01\" -fPIC "-I/home/kthakore/perl5/perlbrew/perls/perl-5.12.0/lib/5.12.0/i686-linux-thread-multi/CORE"  -O2 ZeroMQ.c
.//home/kthakore/perl5/perlbrew/perls/perl-5.12.0/bin/perl5.12.0 -MExtUtils::XSpp::Cmd -e xspp -- -t typemap.xsp ZeroMQ.xsp: In function ‘void XS_ZeroMQ__Socket_setsockopt(PerlInterpreter_, CV_)’:
.//home/kthakore/perl5/perlbrew/perls/perl-5.12.0/bin/perl5.12.0 -MExtUtils::XSpp::Cmd -e xspp -- -t typemap.xsp ZeroMQ.xsp:138: error: ‘length’ was not declared in this scope
.//home/kthakore/perl5/perlbrew/perls/perl-5.12.0/bin/perl5.12.0 -MExtUtils::XSpp::Cmd -e xspp -- -t typemap.xsp ZeroMQ.xsp: In function ‘void XS_ZeroMQ__Message_new(PerlInterpreter_, CV_)’:
.//home/kthakore/perl5/perlbrew/perls/perl-5.12.0/bin/perl5.12.0 -MExtUtils::XSpp::Cmd -e xspp -- -t typemap.xsp ZeroMQ.xsp:244: error: ‘length’ was not declared in this scope
make: **\* [ZeroMQ.o] Error 1

**Comment by kthakore** [comment]
I got this to work by change length(value) to STRLEN_length_of_option_value in the c file.

**Comment by kthakore** [comment]
Made a fork and fixed in this commit. 

http://github.com/kthakore/ZeroMQ-Perl/commit/9a14491c7a0b4ba8c038b7e4861775b8e123c5d4

I sent a pull request out

**Comment by tsee** [comment]
Hi, I forgot to mention that you need a hacked ExtUtils::XSpp for this to work. I'm sorry for the inconvenience. It'll be fixed when I get back home in ~1.5 weeks. Until then, you can grap EU::XSpp from my github account (the lengthFix branch).

**Comment by kthakore** [comment]
Great thanks.
