### ISSUE TITLE
Error on running Make 

### ISSUE THREAD

**Issue by mkirank** [tsee/ZeroMQ-Perl#6]
I get the following error while running make on Centos 5.3  (64 bit) running perl 5.10.1

cp lib/ZeroMQ.pm blib/lib/ZeroMQ.pm
/root/perl5/perlbrew/perls/perl-5.10.1/bin/perl5.10.1 /root/perl5/perlbrew/perls/perl-5.10.1/lib/5.10.1/ExtUtils/xsubpp  -C++ -hiertype -typemap /root/perl5/perlbrew/perls/perl-5.10.1/lib/5.10.1/ExtUtils/typemap -typemap perlobject.map -typemap typemap  ZeroMQ.xs > ZeroMQ.xsc && mv ZeroMQ.xsc ZeroMQ.c
Please specify prototyping behavior for ZeroMQ.xs (see perlxs manual)
g++ -c  -I. -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2   -DVERSION=\"0.01\" -DXS_VERSION=\"0.01\" -fPIC "-I/root/perl5/perlbrew/perls/perl-5.10.1/lib/5.10.1/x86_64-linux/CORE"  -O2 ZeroMQ.c
.//root/perl5/perlbrew/perls/perl-5.10.1/bin/perl5.10.1 -MExtUtils::XSpp::Cmd -e xspp -- -t typemap.xsp ZeroMQ.xsp: In function âvoid XS_ZeroMQ__Socket_setsockopt(CV_)â:
.//root/perl5/perlbrew/perls/perl-5.10.1/bin/perl5.10.1 -MExtUtils::XSpp::Cmd -e xspp -- -t typemap.xsp ZeroMQ.xsp:138: error: âlengthâ was not declared in this scope
.//root/perl5/perlbrew/perls/perl-5.10.1/bin/perl5.10.1 -MExtUtils::XSpp::Cmd -e xspp -- -t typemap.xsp ZeroMQ.xsp: In function âvoid XS_ZeroMQ__Message_new(CV_)â:
.//root/perl5/perlbrew/perls/perl-5.10.1/bin/perl5.10.1 -MExtUtils::XSpp::Cmd -e xspp -- -t typemap.xsp ZeroMQ.xsp:244: error: âlengthâ was not declared in this scope
make: **\* [ZeroMQ.o] Error 1

**Comment by tsee** [comment]
Can you try again after installing the just-released development version 0.11_02 of ExtUtils::XSpp?

**Comment by mkirank** [comment]
The install is good and all the test pass when I upgrade to ExUtils::XSpp 0.11_02. 

Thanks.
