### ISSUE TITLE
make test fails to run all tests

### ISSUE THREAD

**Issue by mankins** [tsee/ZeroMQ-Perl#7]
When I ran "make test" I got the following results:
# make test

PERL_DL_NONLAZY=1 /usr/bin/perl "-MExtUtils::Command::MM" "-e" "test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/01basic.t .. Failed 15/22 subtests 
## Test Summary Report

t/01basic.t (Wstat: 11 Tests: 7 Failed: 0)
  Non-zero wait status: 11
  Parse errors: Bad plan.  You planned 22 tests but ran 7.
Files=1, Tests=7,  0 wallclock secs ( 0.04 usr  0.01 sys +  0.05 cusr  0.03 csys =  0.13 CPU)
Result: FAIL
Failed 1/1 test programs. 0/7 subtests failed.
make: **\* [test_dynamic] Error 255

Using the latest libzmq from trunk, fedora install, perl -V:

Summary of my perl5 (revision 5 version 8 subversion 8) configuration:
  Platform:
    osname=linux, osvers=2.6.18-92.1.10.el5xen, archname=x86_64-linux-thread-multi
    uname='linux xenbuilder2.fedora.redhat.com 2.6.18-92.1.10.el5xen #1 smp wed jul 23 04:11:52 edt 2008 x86_64 x86_64 x86_64 gnulinux '
    config_args='-des -Doptimize=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -Dversion=5.8.8 -Dmyhostname=localhos
t -Dperladmin=root@localhost -Dcc=gcc -Dcf_by=Red Hat, Inc. -Dinstallprefix=/usr -Dprefix=/usr -Dlibpth=/usr/local/lib64 /lib64 /usr/lib64 -Dprivlib=/usr/lib/perl5/5.8.8 -Dsitelib=/usr/lib/p
erl5/site_perl/5.8.8 -Dvendorlib=/usr/lib/perl5/vendor_perl/5.8.8 -Darchlib=/usr/lib64/perl5/5.8.8/x86_64-linux-thread-multi -Dsitearch=/usr/lib64/perl5/site_perl/5.8.8/x86_64-linux-thread-m
ulti -Dvendorarch=/usr/lib64/perl5/vendor_perl/5.8.8/x86_64-linux-thread-multi -Darchname=x86_64-linux -Dvendorprefix=/usr -Dsiteprefix=/usr -Duseshrplib -Dusethreads -Duseithreads -Duselarg
efiles -Dd_dosuid -Dd_semctl_semun -Di_db -Ui_ndbm -Di_gdbm -Di_shadow -Di_syslog -Dman3ext=3pm -Duseperlio -Dinstallusrbinperl=n -Ubincompat5005 -Uversiononly -Dpager=/usr/bin/less -isr -Dd
_gethostent_r_proto -Ud_endhostent_r_proto -Ud_sethostent_r_proto -Ud_endprotoent_r_proto -Ud_setprotoent_r_proto -Ud_endservent_r_proto -Ud_setservent_r_proto -Dinc_version_list=5.8.7 5.8.6
 5.8.5 -Dscriptdir=/usr/bin' 
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=define use5005threads=undef useithreads=define usemultiplicity=define
    useperlio=define d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=define use64bitall=define uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='gcc', ccflags ='-D_REENTRANT -D_GNU_SOURCE -fno-strict-aliasing -pipe -Wdeclaration-after-statement -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -I/usr/include/gdb
m',
    optimize='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic',
    cppflags='-D_REENTRANT -D_GNU_SOURCE -fno-strict-aliasing -pipe -Wdeclaration-after-statement -I/usr/local/include -I/usr/include/gdbm'
    ccversion='', gccversion='4.1.2 20070925 (Red Hat 4.1.2-33)', gccosandvers=''
    intsize=4, longsize=8, ptrsize=8, doublesize=8, byteorder=12345678
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=16
    ivtype='long', ivsize=8, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=8, prototype=define
  Linker and Libraries:
    ld='gcc', ldflags =''
    libpth=/usr/local/lib64 /lib64 /usr/lib64
    libs=-lresolv -lnsl -lgdbm -ldb -ldl -lm -lcrypt -lutil -lpthread -lc
    perllibs=-lresolv -lnsl -ldl -lm -lcrypt -lutil -lpthread -lc
    libc=, so=so, useshrplib=true, libperl=libperl.so
    gnulibc_version='2.7'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-Wl,-E -Wl,-rpath,/usr/lib64/perl5/5.8.8/x86_64-linux-thread-multi/CORE'
    cccdlflags='-fPIC', lddlflags='-shared -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic'

Characteristics of this binary (from libperl): 
  Compile-time options: MULTIPLICITY PERL_IMPLICIT_CONTEXT
                        PERL_MALLOC_WRAP USE_64_BIT_ALL USE_64_BIT_INT
                        USE_ITHREADS USE_LARGE_FILES USE_PERLIO
                        USE_REENTRANT_API
  Built under linux
  Compiled at Aug 28 2008 09:57:44
  @INC:
    /usr/lib64/perl5/site_perl/5.8.8/x86_64-linux-thread-multi
    /usr/lib/perl5/site_perl/5.8.8
    /usr/lib/perl5/site_perl
    /usr/lib64/perl5/vendor_perl/5.8.8/x86_64-linux-thread-multi
    /usr/lib/perl5/vendor_perl
    /usr/lib64/perl5/5.8.8/x86_64-linux-thread-multi
    /usr/lib/perl5/5.8.8
    .

I looked at the test to see if I could figure out what was wrong, and was able to get it to run more tests, and made some mods, but it would hang at the end, and at other various places...

http://drop.io/v8g0n8l

has the modified test, that probably doesn't help you, but may...

**Comment by tsee** [comment]
I'm installing a 5.8.8 now to see whether I can reproduce this.

**Comment by tsee** [comment]
Update: Installation wouldn't work even after patching the known sysv troubles. Further attempts blocking on more spare time.

**Comment by tsee** [comment]
Could you give the release version ZeroMQ 0.01 from CPAN a shot? I expect it to fail the same, but it uses a completely different build system now, so maybe that helped. I expect v0.01 to be available from your CPAN mirror by the end of the day.

**Comment by mankins** [comment]
CPAN Tests still fail.  

## Test Summary Report

t/01basic.t  (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: Bad plan.  You planned 25 tests but ran 0.
t/02threads.t (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: Bad plan.  You planned 5 tests but ran 0.
Files=2, Tests=0,  0 wallclock secs ( 0.05 usr  0.00 sys +  0.08 cusr  0.01 csys =  0.14 CPU)
Result: FAIL
Failed 2/2 test programs. 0/0 subtests failed.
  SMUELLER/ZeroMQ-0.01.tar.gz

**Comment by mankins** [comment]
.02 gets closer.  On make test I now get:

# This is ZeroMQ.pm version 0.02

# Linked against zeromq2 2.0.7

t/000_compile.t .. ok  
t/001_context.t .. ok  
t/002_socket.t ... ok  
t/003_message.t .. ok  
t/004_version.t .. ok  
t/100_basic.t .... 1/25 

at which point it freezes...

**Comment by lestrrat** [comment]
What perl version are you using? I looked at the earlier comments, and I see perl 5.8.8, but you're not supposed to even be able to compile ZeroMQ on perl 5.8.8 at this point.

**Comment by lestrrat** [comment]
I just put the extra magic that would allow compilation on 5.8.8, and the tests works for me.
for the record, my version was compiled with zeromq-2.0.8, perl 5.8.8 w/o threads, and  on a Mac OS X 10.6.4

**Comment by mankins** [comment]
Where is that "Extra magic"? Not released in CPAN, I take it?

I'm using perl -v:
This is perl, v5.8.8 built for x86_64-linux-thread-multi

(with the full -V at the top of this bug).

And 2.0.8.

**Comment by lestrrat** [comment]
sorry, forgot to link http://github.com/lestrrat/ZeroMQ-Perl

**Comment by mankins** [comment]
sorry if this is obvious, but I get:

 # perl Makefile.PL 
Can't locate inc/Module/Install.pm in @INC

**Comment by lestrrat** [comment]
install the following modules:

Module::Install
Module::Install::XSUtil
Module::Install::AuthorTests

These are developer tools and are usually bundled with the distribution, but if
you check out from the repository, you need to have them installed.

**Comment by mankins** [comment]
Some progress and some issues:

> make test
> PERL_DL_NONLAZY=1 /usr/bin/perl "-MExtUtils::Command::MM" "-e" "test_harness(0, 'inc', 'blib/lib', 'blib/arch')" t/_.t xt/_.t
> t/000_compile.t .......... 1/? # 
>    This is ZeroMQ.pm version 0.02_01
>    Linked against zeromq2 2.0.7
> 
> **\* WARNING ***
> 
> You're using libzmq '2.0.7'!
> 
> It is known that when used with libzmq < 2.1, some calls to 
>     $socket->recv()
> does not terminate even when a signal is sent (in such cases you
> need to resort to using SIGKILL). 
> 
> You should really be thinking about upgrading your libzmq to 2.1 or
> higher, and recompile ZeroMQ.pm against the new library.
> 
> ---
> 
> t/000_compile.t .......... ok  
> t/001_context.t .......... ok  
> t/002_socket.t ........... ok  
> t/003_message.t .......... ok  
> t/004_version.t .......... ok  
> t/005_poll.t ............. 1/? Assertion failed: false (zmq.cpp:641)
> t/005_poll.t ............. All 6 subtests passed 
> t/100_basic.t ............ 18/25 make: **\* [test_dynamic] Interrupt

Progress: Now get to 18/25.

Issues: I believe I have version 2.0.9 of the library installed.  I just re-downloaded and compiled.  It is reporting 2.0.7.?

**Comment by lestrrat** [comment]
You're either not installing the new 0mq correctly, or somewhere along your C compiler's path, you have an old 0mq installed. That's about all I can say :/
