### ISSUE TITLE
build failure: undefined constants

### ISSUE THREAD

**Issue by khera** [tsee/ZeroMQ-Perl#9]
zmq 2.0.10 on FreeBSD 7.2/amd64, perl 5.10.1, Installing ZeroMQ 0.05 from cpan.

firstly, cpan will not build the module. I have to hand-install the prerequisite Devel::CheckLib first.  then ultimately it fails when it gets into a cycle trying to install ExtUtils::MakeMaker over and over because it cannot find the version number.

Aside from that, now I'm getting the following errors on manual build.  I cannot find where ZMQ_TYPE or ZMQ_LINGER or the other symbols are supposed to be defined.

In file included from xs/perl_zeromq.xs:2:
xs/perl_zeromq.h:51:30: warning: no newline at end of file
xs/perl_zeromq.xs: In function 'XS_ZeroMQ__Raw_zmq_getsockopt':
xs/perl_zeromq.xs:425: error: 'ZMQ_TYPE' undeclared (first use in this function)
xs/perl_zeromq.xs:425: error: (Each undeclared identifier is reported only once
xs/perl_zeromq.xs:425: error: for each function it appears in.)
xs/perl_zeromq.xs:426: error: 'ZMQ_LINGER' undeclared (first use in this function)
xs/perl_zeromq.xs:427: error: 'ZMQ_RECONNECT_IVL' undeclared (first use in this function)
xs/perl_zeromq.xs:428: error: 'ZMQ_BACKLOG' undeclared (first use in this function)
xs/perl_zeromq.xs:429: error: 'ZMQ_FD' undeclared (first use in this function)
xs/perl_zeromq.xs:457: error: 'ZMQ_EVENTS' undeclared (first use in this function)
gmake: **\* [xs/perl_zeromq.o] Error 1

**Comment by lestrrat** [comment]
looks like your problem was solved in the mailing list, but the current repository (well, the active one anyways) is at http://github.com/lestrrat/ZeroMQ-Perl, so in the future please refer there -- I don't receive the issues unless you file them there.

**Comment by khera** [comment]
the page on http://www.zeromq.org/bindings:perl points here for filing bug reports.
